##
## EPITECH POOL CHALLENGE, 2023
## showstr makefile
##

SRC := \
	showstr.c               \
	../01_putchar/putchar.c \
	../03_put_nbr/put_nbr.c \
	../05_putstr/putstr.c   \
	../06_strlen/strlen.c   \
	tests.c                 \
	../assert_match_stdout.c

include ../shared.mk
