##
## EPITECH POOL CHALLENGE, 2023
## my_put_nbr makefile
##

SRC := \
	put_nbr.c               \
	../01_putchar/putchar.c \
	tests.c                 \
	../assert_match_stdout.c

include ../shared.mk
