##
## EPITECH POOL CHALLENGE, 2023
## isneg makefile
##

SRC := \
	isneg.c                 \
	../01_putchar/putchar.c \
	tests.c                 \
	../assert_match_stdout.c

include ../shared.mk
