##
## EPITECH POOL CHALLENGE, 2023
## putstr makefile
##

SRC := \
	putstr.c                \
	../01_putchar/putchar.c \
	tests.c                 \
	../assert_match_stdout.c

include ../shared.mk
